# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'skurmedel'
tagline:             'Stuff'
description:         'My stuff'
url:                 'https://skurmedel.github.io'
baseurl:             ''
paginate:            3

# About/contact
author:
  name:              Simon

# Custom vars
version:             3.1.4
