# Permalinks
#

permalink:           pretty

# Setup
title:               'skurmedel'
tagline:             'Stuff'
description:         'My stuff'
url:                 'https://skurmedel.github.io'
baseurl:             ''
paginate:            3

# About/contact
author:
  name:              Simon

# Custom vars
version:             3.1.4
